using System.Runtime.CompilerServices;

namespace Internal.Runtime.CompilerServices {
	public static unsafe partial class Unsafe {
		// The body of this method is generated by the compiler.
		// It will do what Unsafe.Add is expected to do. It's just not possible to express it in C#.
		[Intrinsic]
		public static extern ref T Add<T>(ref T source, int elementOffset);

		[Intrinsic]
		public static extern ref TTo As<TFrom, TTo>(ref TFrom source);
	}
}